/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPack;

import javax.swing.JOptionPane;

/**
 *
 * @author Demet Koçhan
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FirstPage() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        f_txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        f_txt_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        f_txt_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f_txt_address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adı");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 250, 53, 17);
        getContentPane().add(f_txt_name);
        f_txt_name.setBounds(180, 240, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soyadı");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 290, 50, 17);
        getContentPane().add(f_txt_surname);
        f_txt_surname.setBounds(180, 280, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefon");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 330, 60, 17);
        getContentPane().add(f_txt_number);
        f_txt_number.setBounds(180, 320, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 370, 50, 17);
        getContentPane().add(f_txt_address);
        f_txt_address.setBounds(180, 360, 180, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login_icon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 410, 90, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_icon.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(342, 13, 60, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login_background_435x561.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -4, 480, 560);

        setSize(new java.awt.Dimension(444, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
       String name = f_txt_name.getText().trim().toUpperCase(); 
       String surname = f_txt_surname.getText().trim().toUpperCase();
       String number = f_txt_number.getText().trim();
       String address =f_txt_address.getText().trim();
       
       if( name.equals("") || surname.equals("") || number.equals("") || address.equals("")){ //boş olup olmadıkları kontrol edilir.
           JOptionPane.showMessageDialog(rootPane, "Lütfen tüm alanları doldurun");
           f_txt_name.requestFocus();
           
       }else{
           

               DB db = new DB();
               int status = db.customerInsert(name, surname, number, address);
               db.close();
               
               if(status>0){
               RegisterPage registerPage = new RegisterPage();
               registerPage.setVisible(true);
               dispose();
               }  
               
               if(status == -1){
               JOptionPane.showMessageDialog(rootPane, "Aynı telefon numarası ile kayıt var");
           }
           
   
           
       }
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       RegisterPage register = new RegisterPage();
       register.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_txt_address;
    private javax.swing.JTextField f_txt_name;
    private javax.swing.JTextField f_txt_number;
    private javax.swing.JTextField f_txt_surname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
